config/routes.rb
Rails.application.routes.draw do
  get 'my_dashboard',to: "dashboards#index"
  get 'open_chats', to: "dashboards#get_open_chats", as: 'open_chats'
  get 'design', to: "designs#index", as: 'meet-the-team'
  # get 'messages/create'
  devise_for :users
  root to: 'pages#home'
  resources :chats, only: [:show, :create, :destroy] do
    resources :messages, only: [:create]
  end
  get 'refresh_chat_banner/:id', to: 'chats#refresh_chat_banner', as: 'refresh_chat_banner'
  get 'emergency_contacts/:user_id', to: "emergency_contacts#index", as: "emergency_contacts"
  patch 'dashboard/:user_id', to: "dashboards#update", as: "dashboard"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :helpee, class_name: "User", optional: true
  belongs_to :helper, class_name: "User", optional: true
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :phone_number, presence: true, uniqueness: true
  validates :opening, presence: true
  validates :closing, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create :broadcast_message

  belongs_to :user
  belongs_to :chat
  validates :content, presence: true, allow_blank: false

  def from?(some_user)
    user == some_user
  end

   def broadcast_message
    ActionCable.server.broadcast("chat_#{chat.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "shared/message",
        locals: { message: self, user_is_messages_author: false }
      ),
      current_user_id: self.user.id
    })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages, dependent: :destroy
  has_many :helper_chats, class_name: "Chat", foreign_key: "helper_id", dependent: :destroy
  has_many :helpee_chats, class_name: "Chat", foreign_key: "helpee_id", dependent: :destroy
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def avatar_url
    if is_helper?
      "profile_pic.png"
    else
    "https://cdn.dribbble.com/users/1068752/screenshots/5401753/new_avatar.jpg"
    end
  end

  def is_helper?
    is_helper
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [ :photo, :photo_cache ])
  end

  def after_sign_in_path_for(resource)
      if resource.is_helper
        helper = resource
        my_dashboard_path
      else
        helpee = resource
        @chat = Chat.create(helpee: current_user)
        chat_path(@chat)
      end
  end

def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]

  def show
    @chat = Chat.includes(messages: :user).find(params[:id])
    if current_user.is_helper?
      @chat.helper = current_user
      @chat.save
    end
    @transparent = true
  end

  def create
    if current_user.nil?
      @helpee = User.create(email: "#{User.last.id + 1}@gmail.com", password: "123456", is_helper: false, username: params[:username])
      sign_in(@helpee, scope: :user)
    end
    @chat = Chat.create(helpee: current_user)
    # @client = Twilio::REST::Client.new ENV['TWILIO_ACCT_SID'], ENV['TWILIO_SECRET_KEY']
    # phone_numbers = ['+45 91 99 30 99', '+45 50 37 35 64']
    # phone_numbers.each do |number|
    # @client.api.account.messages.create(from: '+18042943451', to: number, body: "Hey there. #{current_user.username || 'someone'} wants to talk on Flare.")
    # end

    redirect_to chat_path(@chat)
  end

  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy
    redirect_to root_path
  end

  def refresh_chat_banner
    @chat = Chat.includes(messages: :user).find(params[:id])
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:get_open_chats]

  def index
    @user = current_user
    @open_chats = Chat.where(helper: nil).where.not(helpee: nil)
    @transparent = false
  end

  def get_open_chats
    @open_chats = Chat.where(helper: nil).where.not(helpee: nil)
    respond_to do |format|
      format.js  # <-- idem
    end
  end

  def update
    @user = User.find(params[:user_id])
    @user.update(address: "Ahornsgade 21, 2200")

    redirect_to emergency_contacts_path
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @transparent = true
  end
end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    time = Time.now.to_s[11..15].split(":").join.to_i
    @emergency_contacts = EmergencyContact.where("opening <= ?", time).where("closing >= ?", time)
                          .order(:name)
    if current_user.address?
      @mapped_emergency_contacts = EmergencyContact.where("opening <= ?", time).where("closing >= ?", time)
                                .where.not(address: nil).near(current_user.address, 3)
      @user = {
        lng: current_user.longitude,
        lat: current_user.latitude,
        infoWindow: { content: render_to_string(partial: "shared/user_partial", locals: { user: @current_user }) }
      }
    else
      @mapped_emergency_contacts = EmergencyContact.where("opening <= ?", time).where("closing >= ?", time)
                                .where.not(address: nil)
    end
    @markers = @mapped_emergency_contacts.map do |contact|
      if contact.latitude && contact.longitude
        {
          lng: contact.longitude,
          lat: contact.latitude,
          infoWindow: { content: render_to_string(partial: "emergency_contacts/map_window", locals: { contact: contact }) }
        }
      end
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new(message_params)
    @chat = Chat.find(params[:chat_id])
    @message.chat = @chat
    @message.user = current_user
    if @message.save
      respond_to do |format|
        format.html {
          redirect_to chat_path(@chat)
        }
        format.js
      end
    else
      respond_to do |format|
        format.html {
          render "chats/show"
        }
        format.js
      end
    end

  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @transparent = true
    # cookies[:hello]='hi!'
    # if cookies[:hello]
    #   flash[:notice] = cookies[:hello]
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/chats/refresh_chat_banner.js.erb
 console.log("hello from refresh_chat_banner.js.erb");

 document.querySelector('.chat-header')
 .innerHTML = '<%= j render "shared/chat_banner", chat: @chat %>'

app/views/chats/refresh_chat_first_time.js.erb
console.log("hello from refresh_chat_first_time.js.erb");

 document.querySelector('#message-body')
 .innerHTML = '<%= j render "shared/message", chat: @chat %>'

app/views/chats/show.html.erb
<div class="container-fluid">
  <div class="chat-wrapper  margin-top">
      <div class="messages" id="chatbox">
      <%= audio_tag "sea-waves.mp3", class: "audio-play", id: "playMusic" %>
        <div id="remove-button" class="btn audioButton"><i class="fas fa-volume-up"></i></div>
        <div class="btn stop"><i class="fas fa-volume-off"></i></div>
      <div class="chat-header">
        <%= render 'shared/chat_banner', chat: @chat %>
      </div>
        <% @chat.messages.each do |message| %>

        <%= render "shared/message", message: message, user_is_messages_author: message.user == current_user %>

        <% end %>
      </div>
      <div id="create-message">
        <%= simple_form_for [ @chat, Message.new ], remote: true, html: { class: 'toto' } do |f| %>
          <input class="form-control string required" type="text" name="message[content]" id="message_content">
        <%= f.submit 'Send', class: 'send-button' %>
        <% end %>
      </div>
  </div>
</div>

<%= link_to "Refresh Chat banner", refresh_chat_banner_path(@chat), remote: true, class: "btn btn-primary refresh-chat-banner"   %>


<% content_for :after_js do %>
  <script>
    scrollLastMessageIntoView();
    App['chat_<%= @chat.id %>'] = App.cable.subscriptions.create(
      { channel: 'ChatsChannel', chat_id: <%= @chat.id %> }, {
      received: (data) => {
        if (data.current_user_id !== <%= current_user.id %>) {
          const messagesContainer = document.querySelector('.messages');
          messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
          scrollLastMessageIntoView();
         }
        }
      }
    );
  </script>
  <%= javascript_pack_tag "chatban" %>
  <%= javascript_pack_tag "audio" %>
<% end %>

app/views/dashboards/_edit_user_info.html.erb
<%= simple_form_for(user_registration_path method: :patch) do |f|%>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input(:current_password,{
        hint: "Type in your password to save your changes",
        required: false,
        input_html: { autocomplete: "current-password" }
        }) %>
    </div>
    <div class="form-inputs">
      <%= f.input :username%>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Update" %>
    </div>
<% end %>

app/views/dashboards/_open_chats_list.html.erb
  <h2>Open chats</h2>
  <ul id="chat-list">
    <% chats.each do |chat| %>
      <% if chat.helpee.username? %>
        <li><%= link_to "#{chat.helpee.username.capitalize}", chat_path(chat) %></li>
      <% else %>
        <li><%= link_to "Anon", chat_path(chat) %></li>
      <% end %>
    <% end %>
  </ul>

app/views/dashboards/get_open_chats.js.erb
console.log("Hello from get_open_chats.js.erb");


document.querySelector('.element-open-chats')
.innerHTML = '<h2>Open chats</h2> <%= j render "shared/open_chats_list", chats: @open_chats %>'

app/views/dashboards/index.html.erb
<div class="grid" style="margin-top: 100px;">
  <div class="element-photo element">
    <div class="photo">
      <% if @user.photo? %>
        <%= cl_image_tag @user.photo, size: "220x220", class: "profile-image" %>
      <% else %>
        <%= image_tag "profile_pic.png", size: "220x220", class: "profile-image" %>
      <% end %>
      <h3><%= @user.username %></h3>
    </div>
    <div class="user-info">
        <br>
        <span><%= @user.email %></span>
        <br>
        <br>
      <a href="#" >
        <i class="far fa-edit"></i> <span>Profile Info</span>
        <br>
      </a>
    </div>
  </div>
  <div class="element-open-chats element">
    <%= render "open_chats_list", chats: @open_chats %>
  </div>
  <div class="element element-completed-chats">
    <h2>Completed Chats</h2>
    <h3>326</h3>
  </div>
  <div class="element element-weekly-schedule">
    <h2>Weekly schedule</h2>
    <ul class="week">
      <li><span>MON</span> <span>22:00-03:00</span> <span><a href="#"><i class="far fa-edit"></i></a></span></li>
      <li><span>TUE</span> <span>19:00-23:00</span> <span><a href="#"><i class="far fa-edit"></i></a></span></li>
      <li><span>WED</span> <span class="day-off">DAY OFF</span> <span><a href="#"><i class="far fa-edit"></i></a></span></li>
      <li><span>THU</span> <span class="day-off">DAY OFF</span> <span><a href="#"><i class="far fa-edit"></i></a></span></li>
      <li><span>FRI</span> <span>14:00-20:00</span><a href="#"><i class="far fa-edit"></i></a></span></li>
      <li><span>SAT</span> <span>09:00-15:00</span><a href="#"><i class="far fa-edit"></i></a></span></li>
      <li><span>SUN</span> <span class="day-off">DAY OFF</span> <span><a href="#"><i class="far fa-edit"></i></a></span></li>
    </ul>
  </div>
  <div class="element element-upcoming-training-sessions">
    <h2>Next training</h2>
    <p><span>17.12.2018</span> - Appropriate responses to panic attacks.</p>
  </div>

  <%= link_to "Refresh Chat", open_chats_path, remote: true, class: "btn btn-primary monkeypants"  %>
  <%= content_for :after_js do %>
    <%= javascript_pack_tag "dashboard-refresh" %>
  <% end %>
</div>

app/views/designs/index.html.erb
<div class="container team-page">
<!--       <div class="card-title">
        <h1>Meet our team</h1>
      </div> -->
  <div class="grid team-page-grid">
    <!-- CARD USER -->
    <div class="card-user">
      <div class="card-photo">
        <%= image_tag 'ana.jpg', size: "220x220", class: "profile-image" %>
      </div>
      <div class="name-field">
        <h3>Ana Ivan</h3>
        <p>Product Owner</p>
      </div>
      </div>

    <!-- CARD USER -->
    <div class="card-user">
      <div class="card-photo">
        <%= image_tag 'adline.jpg', size: "220x220", class: "profile-image" %>
      </div>
      <div class="name-field">
        <h3>Adline Isiji</h3>
        <p>Full Stack Developer</p>
      </div>
    </div>
    <!-- CARD USER -->

    <div class="card-user">
      <div class="card-photo">
        <%= image_tag 'irene.jpg', size: "220x220", class: "profile-image" %>
      </div>
      <div class="name-field">
        <h3>Irene Jóna Smith</h3>
        <p>Full Stack Developer</p>
      </div>
    </div>

    <!-- CARD USER -->
    <div class="card-user">
      <div class="card-photo">
        <%= image_tag 'janina.jpg', size: "220x220", class: "profile-image" %>
      </div>
      <div class="name-field">
        <h3>Janina Kokkonen</h3>
        <p>Full Stack Developer</p>
      </div>
    </div>


  </div>
</div>

app/views/emergency_contacts/_map_window.html.erb
<div class="pop-up">
  <h3><%= contact.name %></h3>
  <p><i class="fas fa-home"></i> <%= contact.address %></p>
  <p><i class="fas fa-phone"></i> <%= contact.phone_number %></p>
</div>

app/views/emergency_contacts/index.html.erb
<%= link_to "locate", dashboard_path(current_user), method: :patch, data: { confirm: "Would you like to share your location?"}, id: "locate-user" %>

<div class="emergency-contacts-page-container margin-top" >
  <div
   id="map"
   style="width: 70%;
   height: calc(100vh-200px);"
   data-markers="<%= @markers.to_json %>"
   data-user="<%= @user.to_json if !@user.nil? %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
   data-geolocation-api-key="<%= ENV['IP_GEOLOCATION_KEY'] %>"
  ></div>

  <div class="emergency-contacts scrolling-bar">
    <h3>Open now:</h3>
    <ul class="map-list-names">
      <% @emergency_contacts.each_with_index do |contact, i| %>
        <% if i.even? %>
          <li class="first-background"> <%= contact.name %>
            <ul class="map-list">
              <li><i class="fas fa-phone"></i> <%= contact.phone_number %></li>
            </ul>
          </li>
          <hr>
        <% else %>
          <li class="second-background"> <%= contact.name %>
            <ul class="map-list">
              <li><i class="fas fa-phone"></i> <%= contact.phone_number %></li>
            </ul>
        </li>
        <hr>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Flare - Send a Flare, Get Help</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <title><%= meta_title %></title>
  <meta name="description" content="<%= meta_description %>">

  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />

  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:title" content="<%= meta_title %>">
  <meta name="twitter:description" content="<%= meta_description %>">
  <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
    </div>
  </body>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/create.js.erb
function addMessageToDOM() {
  const messagesContainer = document.querySelector('.messages');
  messagesContainer.insertAdjacentHTML('beforeend', '<%= j render "shared/message", message: @message, user_is_messages_author:true %>');
  const input = document.querySelector('#message_content');
  input.value = '';
  scrollLastMessageIntoView();
  input.focus();
}

<% if @message.errors.any? %>
  // handle validation errors later
<% else %>
  addMessageToDOM();
<% end %>

app/views/pages/home.html.erb
<div class="container-fluid">
<%= render 'shared/banner' %>

<!-- S E C O N D    B A N N E R  -->

<%= render 'shared/secondbanner' %>

<!-- T H I R D    B A N N E R  -->

<%= render 'shared/thirdbanner' %>
</div>

app/views/shared/_banner.html.erb
<div class="container-fluid">
  <div class="banner">
    <div class="banner-text">
      <h1 id="text-cto-h1">We are here for you.</h1>
      <h3 id="text-cto-h3">Get in touch with our trained volunteers, if you are experiencing panic attacks or thoughts of self-harm.</h3>
          <button type="button" class="btn button-banner" data-toggle="modal" data-target=".bs-example-modal-sm">SEND A FLARE</button>
          <%= render "shared/modal" %>
    </div>
  </div>
</div>

app/views/shared/_chat_banner.html.erb
<% if chat.helper.nil? %>
  <p class="no-helper">Someone will be with you soon.</p>
<% elsif chat.helpee == current_user%>
  <p class="added-helper"><%= "You are now chatting with #{@chat.helper.username}" %></p>
<% else %>
  <p class="added-helper">You are now chatting with <%= chat.helpee.username == "" ? "anonymous" : "#{@chat.helpee.username}" %></p>
<% end %>

<%= link_to chat_path(chat), method: :delete do %>
  <i class="fas fa-times" title="End chat and go back to homepage"></i>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="box">
  <div class="box-content">

    <!-- A B O U T  -->

      <div class="box-item">
        <p>ABOUT</p>
          <ul>
            <li><%= link_to 'Meet the team', meet_the_team_path  %></li>
            <li><a href="#">Our mission</a></li>
            <li><a href="#">How it works</a></li>
            <li><a href="#">Website disclaimer</a></li>
          </ul>
      </div>

    <!-- G E T   I N V O L V E D -->

      <div class="box-item">
        <p>GET INVOLVED</p>
          <ul>
            <li><a href="#">Support us</a></li>
            <li><a href="#">Become a volunteer</a></li>
            <li><a href="#">Our Partners</a></li>
            <li><a href="#">FAQ</a></li>
          </ul>
      </div>

    <!-- E X P E R T -->

      <div class="box-item">
        <p>FIND AN EXPERT</p>
          <ul>
            <li><a href="#">Anxiety and Depression Association</a></li>
            <li><a href="#">Find a Therapist</a></li>
            <li><a href="#">Help for Mental Illnesses</a></li>
            <li><a href="#">Statistics</a></li>
          </ul>
      </div>

  </div>
</div>

app/views/shared/_message.html.erb
<div class="message <%= user_is_messages_author ? "right" : "" %>">
  <!-- <p><% message.user.username %></p> -->
  <%= image_tag message.user.avatar_url, class: "avatar" %>
  <div class="message-content"><%= message.content %></div>
</div>

app/views/shared/_modal.html.erb
<!-- Small modal -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <h1>Hello there!</h1>
      <p>Before we go on, please type your first name in the field below.</p>
      <%= form_tag chats_path, method: :post do %>
        <%= text_field_tag :username, "", class: "form-control", placeholder: "First name", id: "placeholder" %>
        <%= submit_tag "Submit", class: "btn btn-modal" %>
      <% end %>
      <% if !user_signed_in? %>
        <div class="sign_in_link">
          <%= link_to("Sign in", "/users/sign_in") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-umbrella navbar-fixed-top <%= @transparent ? "navbar-transparent" : "navbarsnot-transparent" %>">

<!-- Logo  -->

  <%= link_to(root_path) do   %>
  <%= image_tag 'logo-full-basic.png', class: "navbar-umbrella-brand" %>
  <% end %>

<!-- Right Navigation -->

<div class="navbar-right hidden-xs hidden-sm">
<!-- If Helper -->

  <% if user_signed_in? && current_user.is_helper?%>

    <div class="dropdown">
      <% if current_user.photo? %>
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-umbrella-menu", "data-toggle" => "dropdown"%>
        <% else %>
        <%= image_tag 'profile_pic.png', class:'avatar dropdown-toggle', "data-toggle" => "dropdown"%>
      <% end %>
          <ul class="dropdown-menu">
            <li>
              <%= link_to my_dashboard_path do %>
              <p>My Dashboard<span class="fa fa-columns"></span></p>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <p>Log out<span class="fa fa-sign-out-alt"></span></p>
              <% end %>
            </li>
          </ul>
    </div>

<!-- If Helpee -->

  <% elsif user_signed_in? %>

    <div class="dropdown">
      <i class="fas fa-user" class="avatar dropdown-toggle", id="navbar-umbrella-menu", data-toggle="dropdown"></i>
      <ul class="dropdown-menu">
        <li>
          <%= link_to emergency_contacts_path(current_user.id) do %>
           <p>Emergency contacts <span class="fas fa-file-medical"></span></p>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <p>Log out <span class="fa fa-sign-out-alt"></span></p>
          <% end %>
        </li>
      </ul>
    </div>

<!-- If no one logged in -->
  <% else %>
  <div id="volunteeer-login">
    <%= link_to 'VOLUNTEER LOGIN', new_user_session_path %>
  </div>
  <% end %>
</div>

<!-- Dropdown appearing on mobile only -->
<div class="navbar-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fas fa-bars dropdown-toggle" style="color: #282E38"data-toggle="dropdown" role="button"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if user_signed_in? && current_user.is_helper? %>
                  <li>
                    <%= link_to my_dashboard_path do %>
                   <p>My Dashboard<span class="fa fa-columns"></span></p>
              <% end %>
                 </li>
                 <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                    <p>Log out<span class="fa fa-sign-out-alt"></span></p>
                    <% end %>
                  </li>

                <% elsif user_signed_in? %>
              <li>
                <%= link_to emergency_contacts_path(current_user.id) do %>
                <p>Emergency contacts <span class="fas fa-file-medical"></span></p>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <p>Log out <span class="fa fa-sign-out-alt"></span></p>
                <% end %>
              </li>
                <% else %>
              <li>
                  <%= link_to 'Volunteer login', new_user_session_path %>
               </li>
              <% end %>
          </ul>
      </div>
</div>


</div>

app/views/shared/_open_chats_list.html.erb
  <ul id="chat-list">
    <% chats.each do |chat| %>
      <% if chat.helpee.username? %>
        <li><%= link_to "#{chat.helpee.username.capitalize}", chat_path(chat) %></li>
      <% else %>
        <li><%= link_to "Anon", chat_path(chat) %></li>
      <% end %>
    <% end %>
  </ul>

app/views/shared/_secondbanner.erb
  <div class="row" style="background-color: #FFF;">
    <div class="col-md-6">
      <div id="left-text">
        <h3><strong>FLARE</strong> is also available on mobile.</h3>
        <p>You can get in touch with over 150,000 trained volunteers ready to assist you when you are experiencing panic attacks or difficult thoughts.</p>
        <p>You do not need to go though it alone.</br>We are here for you.</p>
        <p>We are here to teach you how to cope.</p>
        <div class="row" style="margin-top: 20px;">
          <%= image_tag 'apple.png', width: 150, class: 'download-apple' %>
          <%= image_tag 'google.png', width: 150, class: 'download-google'%>
        </div>
      </div>
    </div>
    <div class="col-md-6 phone">
      <%= image_tag 'design_iphone.png' %>
    </div>
  </div>

app/views/shared/_user_partial.html.erb
<h3>You are here</h3>